### ISSUE TITLE
IKEA - problem with injected customElements

### ISSUE THREAD

**Issue by UCyborg** [martok/palefill#31]
A web site with interesting problem was brought up on [Pale Moon forum](https://forum.palemoon.org/viewtopic.php?f=70&t=28542).

https://www.ikea.com/gb/en/search/?q=pillows

After adding the rule in /lib/builtin-rules.js to add customElements to www.ikea.com, the following error shows up in the console:

Error: Failed to construct a custom element: The constructor was not registered with customElements.

**Comment by martok** [comment]
Turns out that even has a comment in the polyfill's source. https://github.com/webcomponents/polyfills/blob/master/packages/custom-elements/ts_src/Patch/HTMLElement.ts#L20
As far as I can tell, we have new.target on all platforms, so we can just use that.

**Comment by UCyborg** [comment]
Looks like Custom Elements aren't enough for IKEA. Rendering on the search page remains incomplete along with the message about outdated browser.

**Comment by martok** [comment]
I see `TypeError: Function.prototype.toString called on incompatible object` for what is basically `Function.toString.call(new Proxy(document.addEventListener, {}))`. This used to be forbidden but was apparently changed (for example, the ancient german translation of [MDN still mentions it](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Function/toString)).

This was [Bugzilla 1440468](https://bugzilla.mozilla.org/show_bug.cgi?id=1440468), I think it makes more sense to fix this in UXP than here, even if it takes longer since it looks like I might just miss 31.2...
