### ISSUE TITLE
Consider listing your extension on the Pale Moon Add-ons Site

### ISSUE THREAD

**Issue by FranklinDM** [martok/palefill#32]
Hi,

I'm FranklinDM from the Pale Moon Add-ons Team. Would you be interested in listing your extension on the Pale Moon Add-ons Site? We have two (2) available options for you to choose from:
1. Hosting your add-on
> The service will provide full hosting of your add-on, a dedicated page, and automatic update services.
>
> For this option, you'll need to create an account on [Phoebus](https://addons.palemoon.org/panel/) and submit your extension for review.
2. Indexing your add-on
> This is known informally as an External. Indexing is available to both extensions and themes will list your extension to the category of your choosing and will link to where users can obtain your extension.
>
> This solution is a great choice for maintaining your independence and choice of infrastructure and distribution. You may, for example, want to host your extension on your own website or source code repository's downloads section.

I've reviewed your extension and everything looks good to me in terms of code, except for the name. It implies that it is an official extension made by the developers of Pale Moon (e.g., [Pale Moon Commander](https://addons.palemoon.org/addon/pm-commander/) and [Pale Moon Locale Switcher](https://addons.palemoon.org/addon/locale-switcher/)). You might want to move it to the end instead, like "Web Technologies Polyfill Add-on for Pale Moon", or even "Palefill" is fine. Either way, I'll leave that for you to decide.

For more information, you may refer to the following page: http://developer.palemoon.org/addons/site/

If you have any further questions, feel free to let me know. Thank you!

**Comment by martok** [comment]
Hi,

It's pretty wild how much the user base and usefulness here has grown from way back when I basically just put this on Github so that my hand full of devices have something to update from. So yeah, why not officially tell people that this thing exists.

I think the easiest and way would be to stay external, just so I can continue to do all release management here.

> except for the name. It implies that it is an official extension made by the developers of Pale Moon (e.g., [Pale Moon Commander](https://addons.palemoon.org/addon/pm-commander/) and [Pale Moon Locale Switcher](https://addons.palemoon.org/addon/locale-switcher/)). You might want to move it to the end instead, like "Web Technologies Polyfill Add-on for Pale Moon", or even "Palefill" is fine.

I will absolutely do that. I'd like to keep "Palefill" if that's ok, just because I like stupid punny names :smile: 

A few things to do, then:

- [ ] Addon Name
- [ ] Addon Icon (64x64 32bpp)
- [ ] Landing page using Github Pages
- [ ] Split docs to landing/user/developer info
- [ ] Update URLs in RDF etc.
- [ ] Register on AMO

**Comment by l29ah** [comment]
for an icon i would suggest the palemoon icon with top cut out and getting filled with water, but that would violate moonchild copyright and trademark and whatnot, and no one will draw it anyway...

**Comment by garoto** [comment]
> Addon Icon (64x64 32bpp)

Just generate a nearest-neighbor upscaled version of your GH avatar and it should be good enough.

**Comment by garoto** [comment]
On a not-so-related-note, it depresses and amuses me at the same time that tobin spent years "working" and kept bragging about what in the end turned out to be such a lackluster, mundane, PHP upload interface. I mean, people were doing better looking, more functional PHP CMS interfaces in their spare time in ~2004.

Cherry on the cake was baptizing the whole thing with a pretentious name.

(feel free to minize/hide this comment, I just wanna vent a little)

**Comment by martok** [comment]
Aaaand [we're live](https://addons.palemoon.org/search/?terms=palefill)!
