### ISSUE TITLE
Can it be used to force discord work?

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [martok/palefill#58]
https://discord.com/app - this sh*t

**Comment by martok** [comment]
Language, young padawan.

Also: I highly doubt this is going to work in a meaningful way, for instance Pale Moon doesn't support WebRTC. Doubt it enough anyway that _I'm_ not going to invest any time in it. Pull requests are of course always welcome if anyone wants to do it.

Use the desktop client or a modern browser, if you must.

**Comment by Vangelis66** [comment]
> I highly doubt this is going to work in a meaningful way, 
> for instance Pale Moon doesn't support WebRTC.

FWIW, `discord web` used to work (somewhat sluggishly 😜 ) in **UXP-based** browsers, albeit for just **chatting/texting**, ca. **7 months ago**, before they went all Chromium-only 😡 ... FTR, **current** deal-breaker seems to be: 
```
SyntaxError: invalid identity escape in regular expression (in file:) https://discord.com/assets/b7b959491def14051c8a.js:149:225

Stack trace:
[212563]@https://discord.com/assets/a9a8712c15f082786468.js:841:815
l@https://discord.com/assets/54d80d2ef88559430452.js:1:149
[950884]@https://discord.com/assets/a9a8712c15f082786468.js:650:99
l@https://discord.com/assets/54d80d2ef88559430452.js:1:149
[571570]@https://discord.com/assets/4462b534b25c32db2624.js:1670:777
l@https://discord.com/assets/54d80d2ef88559430452.js:1:149
[280491]@https://discord.com/assets/4462b534b25c32db2624.js:407:965
l@https://discord.com/assets/54d80d2ef88559430452.js:1:149
a@https://discord.com/assets/b7b959491def14051c8a.js:66:445
A/<@https://discord.com/assets/b7b959491def14051c8a.js:66:595
c@https://discord.com/assets/b7b959491def14051c8a.js:25:813
```
According to [this](https://msfn.org/board/topic/182647-my-browser-builds-part-3/?do=findComment&comment=1227072) MSFN post, the `SyntaxError` is due to missing [Regex Unicode Property Escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes) support in **UXP** 😭 ...

Pale Moon Forums link: https://forum.palemoon.org/viewtopic.php?p=232312#p232312
**UXP** related issues,  
 https://repo.palemoon.org/MoonchildProductions/UXP/issues/1282
=> https://repo.palemoon.org/MoonchildProductions/UXP/issues/1286 [closed, unresolved]
=> https://repo.palemoon.org/MoonchildProductions/UXP/issues/1675 [closed, won'tfix] 
... seemingly "hitting a brick wall" 😞 ...

**Comment by NEO-SPECTRUMAN** [comment]
also 
is there a way to patch/autoreplace code in .js for certain site?
