### ISSUE TITLE
Serious memory leak in Github "Feature Preview" window.

### ISSUE THREAD

**Issue by Stargate38** [martok/palefill#68]
Palefill version: 1.25
Pale Moon version: 31.4.1.1

Steps to reproduce:

1. Login to your Github account.
2. Click on your pfp (in the top-right corner).
3. Select "Feature Preview".
4. Click "Project Migration".

What happens: Memory usage increases until PC freezes or PM crashes.

Any idea why this happens?

**Comment by Vangelis66** [comment]
Also confirmed in another **UXP**-based browser, **Serpent 52.9.0**; RAM consumption practically **explodes within seconds** 😞 ...

Hard to tell whether this is solely **UXP-related** or not, because that **GitHub** feature is inaccessible without the `palefill` extension... 

I guess I was lucky I was never tempted to enable _that_ feature preview 😜 ; of the three options currently offered, I've only enabled `Colorblind themes`...

**Comment by martok** [comment]
Definitely caused by the absurd GIF preview video, Waterfox has the same issue (Firefox doesn't, interestingly). Reported on UXP#2073, nothing to be done here.

**Comment by Vangelis66** [comment]
> Hard to tell whether this is solely **UXP-related** or not

So, that was indeed **platform**-related (but **GitHub**/Microsoft are the ones to really blame, for not providing **a proper video clip** instead of that _massive_ GIF 😠 ); from [UXP #2073](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2073) it emerges that **Mozilla** dealt with this issue via [#523950](https://bugzilla.mozilla.org/show_bug.cgi?id=523950) (enabled in Fx**62**), but, as **Moonchild** notes: 

> they went the route of **discarding decoded frames** and effectively **trading off a ton of CPU for memory**.
