### ISSUE TITLE
Wordpress.com can't login

### ISSUE THREAD

**Issue by Disil** [martok/palefill#72]
This issues sucked. It started all the way back in 2021, when the login page suddenly inaccessible in PM, only showed the Wordpress logo. And, in early 2022, it started to work fine, until around october. In December, i tried again, and it doesnt work again, like 2021. 

Console said window.appboot is not a function.

Hardware specs:
Pale Moon 31.4.2
Xubuntu 21.10
Intel Celeron N5100

**Comment by Vangelis66** [comment]
> Console said: 
> 
> TypeError: **window.AppBoot is not a function**

... And:  
```
SyntaxError: expected expression, got '='  in minified script 
https://wordpress.com/calypso/evergreen/entry-login.c1b158ad039ab905851d.min.js:1:109779
```
right above it 😉 ...

**Comment by Pravaqt** [comment]
Wordpress offers inaccessibility due to following reasons:

- **Authentication issues**, when the password and username is spelled incorrectly, if you are adding right credentials, check the Mysql database if accessible, if its working you can try to add a new user. 

- **Issues from the content**, plugin and themes usually are seen at fault in such errors, best way would be to, disable all your plugins from database(Mysql) and add default themes/template , example, Twentytwenty. 

- Many a clients using Wordpress from cPanel/Plesk and using CDN services from Cloudflare can have issue from the Firewall. 
**Firewall** actually prevents access from any unauthorized, its good to have it . But you can disable it for timebeing. Try using an IP address with good reptation, avoid connecting to your server from public internet services, such as Hotel Wifi etc. 

- One must check if the linux server is under **DDoS attack** (also known as mitigation), if you have a root access, you can simply review the IP addresses attacking your server and suspend  the IP addresses. If you dont use Root/parent access control,  you can simply request your Hosting providers for the same, its nothing to be afraid of, it would be automaticaly resolved in some time.

**Comment by Disil** [comment]
> Wordpress offers inaccessibility due to following reasons:

No. Wordpress.com is not the same as Wordpress.org, which is self hosted. The .com is hosted by WordPress themselves, and users can use it for free.

It's different from the .org instance, which you need to employ it on server.

**Comment by martok** [comment]
Apparently Wordpress is one of the first users of the new logical assignment operators (`??=` in this case). Just got a ticket upstream: [UXP#2097](https://repo.palemoon.org/MoonchildProductions/UXP/issues/2097).

**Comment by Vangelis66** [comment]
> Wordpress is **one of the first users** of the new logical assignment operators (**??=** in this case).

... Actually, one of several 😠 ; e.g., "**discourse**" are now using it, thus potentially breaking. **under UXP**, all forums based on their "platform": 

https://msfn.org/board/topic/184051-my-browser-builds-part-4/?do=findComment&comment=1237341

To add insult to injury, `notion.*` (#4) **has been broken** a few days ago because of "**??=**", also 😡 ...
