### ISSUE TITLE
[Github] With Palemoon v31.4.2, github's frontpage stopped showing timestamps in my followed feed

### ISSUE THREAD

**Issue by garoto** [martok/palefill#84]
First off, I must disclaim that I have no idea if this belongs in this repo or not or even if upgrading to Palemoon latest will fix it, but I'm reporting it here anyway in the hope it's useful and not a nuisance.

Image comparison showing what it looks like currently:

![screenshot-0785-13-02-2023](https://user-images.githubusercontent.com/11768175/218520029-d2494793-1e91-4751-a809-1f7f4500a06a.png)

vs what it should look like (from Firefox v9x.y): 

![screenshot-0786-13-02-2023](https://user-images.githubusercontent.com/11768175/218520480-c66130d0-fc1f-4762-b508-09c720398703.png)

Error message in Palemoon's "Error console": 

```
Timestamp: 13-Feb-23 13:45:08
Error: RangeError: invalid value unit for option style
Source File: https://github.githubassets.com/assets/vendors-node_modules_github_relative-time-element_dist_index_js-52e1ce026ad1.js
Line: 1
```

Thank you for reading.

**Comment by Vangelis66** [comment]
I can also replicate what you're reporting, with: 
**Serpent 52.9.0** (2023-02-02) (32-bit), 
**palefill**-v1.26-6-git-20230204-g7d4e837, 

when being **logged-in** to my GH account and navigating to: 
https://github.com/

From the `Web Console` error:
```
RangeError: invalid value unit for option style 
vendors-node_modules_github_relative-time-element_dist_index_js-52e1ce026ad1.js:1:2675
```
it appears it's a **known** **UXP** platform shortcoming: 
https://repo.palemoon.org/MoonchildProductions/UXP/issues/2046

The issue is **open**, which means it _might_ be resolved once a competent **UXP** developer solves all the necessary "riddles" :wink: ...

In the interim, perhaps an attempt to "polyfill" the missing JS functions via `palefill` itself should be considered... But it's up to the extension's maintainer 😄 ...

**Comment by garoto** [comment]
Closing since Shithub fixed this themselves.
