### ISSUE TITLE
Palemoon "Ghost Window" issue is still a thing on my setup when running WITHOUT palefill

### ISSUE THREAD

**Issue by garoto** [martok/palefill#99]
Previous "ghost window" Palemoon issue: https://github.com/martok/palefill/issues/50

Using latest Palemoon (palemoon-32.5.2.win64-avx2.installer.exe (yes the avx2 compiles)), and this is still a thing for me when I _heavily_ browse github, and by `heavily` I mean clicking on commits, PRs, etc, the basic source code diff drill exposed by the GH web-interface.

I spent months browsing GH without any addon(s) interfering with the DOM whatsoever (disabled uBlock for the domain, disabled CleanLinks2 for the domain, disabled Greasymokey for the the domain, blacklisted ALL DOM interfering scripts/addons for the domain so I coud troubleshoot properly), and still, WITHOUT palefill being enabled and running, Palemoon WILL behave just like it used to some two/three years ago: CPU usage spikes every X seconds after a session full of Shithub browsing.

Am I the only one? It can't possibly be right?

**Comment by garoto** [comment]
It appears MC, since moving his SW projects away from GH, just doesn't "give a damn" anymore about the state of this website when rendered in his pet web-browser.

Did MC even produced a single C++ line of code in the past two years or so? Browsing thru the repo, it doesn't seem so. If it wasn't for the efforts of all the 3rd party code churning people and their PRs, the browser would've being pretty much fricking DEAD by now.

**Comment by martok** [comment]
What is it with people being weird today? Something in the water?

1. If you're confirming that #50 still exists, then *why did you open a new issue*? Especially since neither me nor @cyanlillies ever managed to get a 100% reliable test case that could be used for debugging. Closing as duplicate.

2. If you just want to drop a generic rant, find another platform. Get a blog or whatever. Closing as off-topic.

3. That's easy to verify if you actually cared.
```
$ git shortlog -sn --since=2.years.ago
   815  Moonchild
   214  Brian Smith (dbsoft)
   199  FranklinDM
   185  Martok
   152  Job Bautista
    62  Jeremy Andrews
    44  trav90
    42  Basilisk-Dev
    18  Matheus Marinho
    16  Matt A. Tobin
    13  athenian200
```

4. Yes indeed, open source projects without contributors spending their free time on it just because we can often run into problems.
